Feat: Flag for chat completion token count
SychAndrii/infusion pull request #21
Opened 2024-09-16 23:17 UTC by aamfahim

# Description
Closes #20 
Added new flag `-u` or `--token-usage`, when given prints the number of tokens that were sent in the prompt and the number of tokens that were returned in the completion to `stderr`.
# Testing
Can be tested by doing any of the following 

```bash
python -m src.app  example/input/DataProcessor.TS --token-usage
```

or 

```bash
python -m src.app  example/input/DataProcessor.TS -u
```

2024-09-16 23:18 UTC, aamfahim commented
For context how it works on my side

![Screenshot 2024-09-16 191156](https://github.com/user-attachments/assets/11ad8498-7269-4de7-a552-4114c511915c)

2024-09-17 02:31 UTC, SychAndrii requested changes
1) Change _completion_ term to _response_
2) Instead of calling ```output_token_usage``` function with two parameters, call it with one that's always going to be used.
3) Construct the chain conditionally

2024-09-17 02:31 UTC, SychAndrii commented on README.md
> +- `-u, --token-usage`: Show the number of tokens that were sent in the prompt and returned in the completion
_Completion_ term is a bit unintuitive. Rename it to _response_.

2024-09-17 02:31 UTC, SychAndrii commented on src/controllers/click_controller.py
> +    @click.option("-u","--token-usage", is_flag=True, help="Show the number of tokens that were sent in the prompt and returned in the completion")
Same with renaming here.

2024-09-17 02:31 UTC, SychAndrii commented on src/controllers/click_controller.py
> +    return response
If ```token_usage_flag``` is false - this function does nothing. I think it is better to call this function **only if** there was token usage flag specified. This way, this function will accept only 1 parameter and it will be easier to understand

2024-09-17 02:31 UTC, SychAndrii commented on src/controllers/click_controller.py
> +
Here I would prefer if you constructed the chain conditionally. So If token usage flag was specified - you include lambda function. Otherwise you don't include it.

2024-09-17 04:19 UTC, aamfahim commented on README.md
> +- `-u, --token-usage`: Show the number of tokens that were sent in the prompt and returned in the completion
resolved with https://github.com/SychAndrii/infusion/pull/21/commits/d305bdfa0bdc7e44a2361dfe82d26b379c3bc665

2024-09-17 04:19 UTC, aamfahim commented on src/controllers/click_controller.py
> +    @click.option("-u","--token-usage", is_flag=True, help="Show the number of tokens that were sent in the prompt and returned in the completion")
resolved with https://github.com/SychAndrii/infusion/pull/21/commits/d305bdfa0bdc7e44a2361dfe82d26b379c3bc665

2024-09-17 04:20 UTC, aamfahim commented on src/controllers/click_controller.py
> +    return response
resolved with https://github.com/SychAndrii/infusion/pull/21/commits/ce85ceed37c7769d753c8d0373fd6d870167a2c7

2024-09-17 04:20 UTC, aamfahim commented on src/controllers/click_controller.py
> +
resolved with https://github.com/SychAndrii/infusion/pull/21/commits/ce85ceed37c7769d753c8d0373fd6d870167a2c7

2024-09-17 17:01 UTC, SychAndrii commented on src/controllers/click_controller.py
> +
Ok, so the function for printing the tokens was fixed, but here the empty lambda you are passing to RunnableLambda can be confusing. I would prefer if you used their RunnablePassthrough function to mark function as simply passing value.
You can look it up here: https://python.langchain.com/docs/how_to/passthrough/

2024-09-17 17:14 UTC, aamfahim commented on src/controllers/click_controller.py
> +
resolved with https://github.com/SychAndrii/infusion/pull/21/commits/124907a4e20edf9029d2ca5bc3ba6ae574125485

2024-09-17 17:16 UTC, SychAndrii approved these changes
Well done!

2024-09-17 17:16 UTC, merged